# https://github.com/ansible/ansible/issues/30754
- name: Install yq
  become: True
  get_url: 
    url: https://github.com/mikefarah/yq/releases/download/3.2.1/yq_linux_amd64
    dest: /usr/local/bin/yq
    mode: '755'