- name: Download vault
  become: true
  unarchive:
    src: https://releases.hashicorp.com/vault/1.3.2/vault_1.3.2_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
  args:  
    creates: /usr/local/bin/vault
  tags: vault